# Part 1. Python Basic with Numpy (optional assignment)


## 1 - Building basic functions with numpy

### 1.1 Sigmoid function, np.exp()

In [1]:
import math

def basic_sigmoid(x):
    """
    Compute sigmoid of x.
    
    Argument:
        x -- A scalar
        
    Return:
        s -- sigmoid(x)
    """
    s = 1.0/(1+ math.exp(-x))
    
    return s

basic_sigmoid(3)

0.9525741268224334

In [2]:
import numpy as np

def sigmoid(x):
    """
    Compute the sigmoid of x.
    
    Argument:
        x -- A scalar or numpy array of any size.
        
    Return:
        s -- sigmoid(x)
    """
    s = 1.0 / (1 + np.exp(-x))
    return s

sigmoid(np.array([1, 2, 3])).round(4)

array([ 0.7311,  0.8808,  0.9526])

### 1.2 Sigmoid gradient

In [3]:
def derivative_sigmoid(x):
    """
    Compute the gradient (also called the slope or derivate) of the sigmoid function 
    with respect to its input x.
    You can store the output of the sigmoid function into variables and then use it to 
    calculate the gradient.
    
    Argument:
        x -- A scalar or numpy array.
        
    Return:
        ds -- The computed gradient.
    """
    s = 1.0 / (1 + np.exp(-x))
    ds = s * (1-s)
    return ds

derivative_sigmoid(np.array([0, 1, 2, 3]))

array([ 0.25      ,  0.19661193,  0.10499359,  0.04517666])

### 1.3 Reshaping arrays

In [4]:
def image2vector(image):
    """
    Vectorization of an image.
    
    Argument:
        image -- a numpy array of shape (length, height, depth)
        
    Return:
         v -- a vector of shape (length * height * depth, 1)
    """
    
    v = image.reshape((image.shape[0] * image.shape[1] * image.shape[2], 1))
    # v = image.reshape((np.prod(np.array(image.shape)) , 1))
    return v


image_test = np.random.rand(3, 3, 2)
print(image_test)
print(image2vector(image_test))

[[[ 0.39198431  0.10046023]
  [ 0.31683415  0.3854926 ]
  [ 0.01825868  0.74008314]]

 [[ 0.30652516  0.73750956]
  [ 0.30883552  0.25618362]
  [ 0.93577042  0.06871725]]

 [[ 0.87789599  0.16442596]
  [ 0.54854824  0.28195541]
  [ 0.63825586  0.94875713]]]
[[ 0.39198431]
 [ 0.10046023]
 [ 0.31683415]
 [ 0.3854926 ]
 [ 0.01825868]
 [ 0.74008314]
 [ 0.30652516]
 [ 0.73750956]
 [ 0.30883552]
 [ 0.25618362]
 [ 0.93577042]
 [ 0.06871725]
 [ 0.87789599]
 [ 0.16442596]
 [ 0.54854824]
 [ 0.28195541]
 [ 0.63825586]
 [ 0.94875713]]


### 1.4 Normalizing rows

In [5]:
def normalizeRows(x):
    """
    Implement a function that normalizes each rows of the matrix x (to have unit length).
    
    Argument:
        x -- A numpy matrix of shape (n, m)
        
    Return:
        x -- The normalized (by row) numpy matrix.
             You are allowed to modify x.
    """
    x_norm = np.linalg.norm(x, axis=1, keepdims=True)
    x = x / x_norm
    return x

x = np.array([[0, 3, 4],
              [1, 6, 4]])
normalizeRows(x)

array([[ 0.        ,  0.6       ,  0.8       ],
       [ 0.13736056,  0.82416338,  0.54944226]])

### 1.5 Broadcasting and the Softmax function

In [6]:
def softmax(x):
    """
    Compute the softmax for each row of the input x.
    
    Argument:
        x -- A numpy matrix of shape (n, m).
    Return:
        s -- A numpy matrix equal to the softmax of x, of shape (n, m).
    """
    x_exp = np.exp(x)
    x_exp_sum = np.sum(x_exp, axis=1, keepdims=True)
    s = x_exp / x_exp_sum
    return s

x = np.array([[9, 2, 5, 0, 0], 
              [7, 5, 0, 0, 0]])
softmax(x)

array([[  9.80897665e-01,   8.94462891e-04,   1.79657674e-02,
          1.21052389e-04,   1.21052389e-04],
       [  8.78679856e-01,   1.18916387e-01,   8.01252314e-04,
          8.01252314e-04,   8.01252314e-04]])

### 1.6 Vectorization

In [7]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i]*x2[i]
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC OUTER PRODUCT IMPLEMENTATION ###
tic = time.process_time()
outer = np.zeros((len(x1),len(x2))) # we create a len(x1)*len(x2) matrix with only zeros
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i]*x2[j]
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j]*x1[j]
toc = time.process_time()
print ("gdot = " + str(gdot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")


dot = 278
 ----- Computation time = 0.0ms
outer = [[ 81.  18.  18.  81.   0.  81.  18.  45.   0.   0.  81.  18.  45.   0.
    0.]
 [ 18.   4.   4.  18.   0.  18.   4.  10.   0.   0.  18.   4.  10.   0.
    0.]
 [ 45.  10.  10.  45.   0.  45.  10.  25.   0.   0.  45.  10.  25.   0.
    0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [ 63.  14.  14.  63.   0.  63.  14.  35.   0.   0.  63.  14.  35.   0.
    0.]
 [ 45.  10.  10.  45.   0.  45.  10.  25.   0.   0.  45.  10.  25.   0.
    0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
    0.]
 [ 81.  18.  18.  81.   0.  81.  18.  45.   0.   0.  81.  18.  45.   0.
    0.]
 [ 18.   4.   4.  18.   0.  18.   4.  10.   0.   0.  18.   4.  10.   0

In [8]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print ("gdot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")


dot = 278
 ----- Computation time = 0.0ms
outer = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
 ----- Computation time = 0.0ms
elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 ----- Computation time = 0.0ms
gdot = [ 25.32141645  26.59991649  29.9079191 ]
 ----- Computation time = 15.600099999999

### 2.1 Implement the L1 and L2 loss functions

In [9]:
def L1(yhat, y):
    """
    Arguemnts:
        yhat -- vector of size m (predicted lables)
        y -- vector of size m (true labels)
        
    Return:
        loss -- the value of the L1 loss function defined above
    """
    loss = np.sum(np.abs(y - yhat))
    return loss

yhat = np.array([.9, .2, .1, .4, .9])
# yhat = np.array([9, 2, 1, 4, 9]) / 10.0
y = np.array([1, 0, 0, 1, 1])
print("L1 = {}".format(L1(yhat, y)))

L1 = 1.1


In [10]:
def L2(yhat, y):
    loss = np.sum(np.power(y-yhat, 2))
    return loss

yhat = np.array([.9, .2, .1, .4, .9])
# yhat = np.array([9, 2, 1, 4, 9]) / 10.0
y = np.array([1, 0, 0, 1, 1])
print("L2 = {}".format(L2(yhat, y)))

L2 = 0.43
